import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja-jp">
      <head>
        <script src="https://cdn.master.co/css"></script>
      </head>
      <body style={{
        margin: 0,
        padding: 0,
      }}>
        {children}
      </body>
    </html>
  )
}
